minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@jsr/mkvlrn__app-error"
  - "@mkvlrn/app-error"
  - "@jsr/mkvlrn__result"
  - "@mkvlrn/config"
  - "@jsr/mkvlrn__config"
  - "@mkvlrn/result"
saveExact: true
