[tools]
biome = "2.5.14"
cocogitto = "7.0.0"
lefthook = "2.1.14"
node = "26.9.0"
pnpm = "12.5.1"

[hooks]
postinstall = "mise run postinstall-hook"

[env]
_.path = ["./node_modules/.bin"]

[settings]
disable_backends = ["asdf"]
use_versions_host = false
minimum_release_age = "1d"

[task_config]
includes = [".config/tasks"]
